### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by fchaxel** [stefan-schindler/plc-programmable-3d-simulation#3]
Hi,

Good job.

No source code available ?

NetToPlcSim could be avoided using the S7ProSim Com Object, see https://www.youtube.com/watch?v=1_21x_W57Ig (part 2).

Using this way the communication between the .NET code and PlcSim is direct (Connect, Disconnect, Continue, SetScanMode, WriteInputImage and ReadOutputImage methods provided by the S7ProSimClass interop wrapper are OK).

Bye.

**Comment by stefan-schindler** [comment]
Hi, thanks for pointing that out :) The source code is not included, because it's whole Unity project with all 3D models, textures, settings and pretty hard to customize.
